mkdir: cannot create directory ‘/disk/scratch/s1890594/data/DescribableTextures’: No such file or directory
sending incremental file list
rsync: mkdir "/disk/scratch/s1890594/data/DescribableTextures" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]
use 6 GPU(s)
[('continue_from_epoch', '-1'), ('seed', '0'), ('task', 'regression'), ('use_gpu', 'True'), ('gpu_id', '0,1,2,3,4,5'), ('model_name', 'context_encoder'), ('kernel_size', '4'), ('num_layers_enc', '6'), ('num_channels_enc', '64'), ('num_channels_progression_enc', '[1, 1, 2, 4, 8]'), ('num_channels_bottleneck', '4000'), ('num_layers_dec', '5'), ('num_channels_dec', '64'), ('num_channels_progression_dec', '[8, 4, 2, 1]'), ('dataset_name', 'DescribableTextures'), ('num_image_channels', '3'), ('image_height', '128'), ('image_width', '128'), ('normalisation', 'range-11'), ('debug_mode', 'False'), ('num_workers', '6'), ('augment', 'False'), ('gamma_factor', '1'), ('rot_angle', '0'), ('translate_factor', '[0, 0]'), ('scale_factor', '1'), ('shear_angle', '0'), ('patch_mode', 'True'), ('patch_size', '[128, 128]'), ('patch_location_during_training', 'central'), ('patch_rejection_threshold', '10'), ('mask_size', '[64, 64]'), ('batch_size', '100'), ('loss', 'L2'), ('num_epochs', '100'), ('learning_rate', '0.0002'), ('betas', '[0.5, 0.999]'), ('weight_decay_coefficient', '0'), ('experiment_name', 'CE_DTD_central_patch_test_1')]
Loading data from:  /disk/scratch/s1890594/data/DescribableTextures
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    train_data, val_data, test_data, num_output_classes = data_providers.create_dataset(args, augmentations, rng)
  File "/mnt/mscteach_home/s1890594/mlp_framework/data_providers.py", line 1272, in create_dataset
    trainset = DescribableTextures(which_set='train', transformer=transform_train, **kwargs_dataset)#, patch_rejection_threshold=patch_rejection_threshold)
  File "/mnt/mscteach_home/s1890594/mlp_framework/data_providers.py", line 776, in __init__
    debug_mode=debug_mode, patch_mode=patch_mode, patch_size=patch_size, patch_location=patch_location, mask_size=mask_size) #, patch_rejection_threshold):
  File "/mnt/mscteach_home/s1890594/mlp_framework/data_providers.py", line 660, in __init__
    self.image_list = os.listdir(self.image_path) #directory may only contain the image files, no other files or directories
FileNotFoundError: [Errno 2] No such file or directory: '/disk/scratch/s1890594/data/DescribableTextures/train'
